### ISSUE TITLE
Issue with tools.plot_tools

### ISSUE THREAD

**Issue by devinross** [Basket-Analytics/BasketTracking#2]
Running 
`python3 main.py --video ../sample_data/lebron_on_court.mp4`

yields the following error for me, but I can seem to install a module that will prevent this issue. Any suggestions?
```
Traceback (most recent call last):
  File "/Users/devinross/Downloads/BasketTracking-master/main.py", line 5, in <module>
    from ball_detect_track import BallDetectTrack
  File "/Users/devinross/Downloads/BasketTracking-master/ball_detect_track.py", line 4, in <module>
    from tools.plot_tools import plt_plot
ModuleNotFoundError: No module named 'tools.plot_tools'
```

**Comment by CrisSherban** [comment]
Hi @devinross,

Unfortunately, we have not provided a proper Python package for this repo.
I have pushed a small update (https://github.com/Basket-Analytics/BasketTracking/commit/a00643d3c6dd448ae0f2f979263ea99fa1bba644) that should fix the `ModuleNotFoundError`.

Please `git pull`and let me know if it works.


P.S. Re-running the example, I faced a small issue with detectron2 and PIL: https://github.com/facebookresearch/detectron2/issues/5010, make sure you have an up to date version of it in case you happen to face it.
